name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Import gpg key
        run: echo $GPG_PRIVATE_KEY | gpg --import
      - name: Release with nexus-staging-maven-plugin
        run: mvn -B -P release deploy --file pom.xml