name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - shell: bash
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_LOGIN: ${{ secrets.OSSRH_LOGIN }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        run: |
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes
      - name: Release with nexus-staging-maven-plugin
        run: mvn -B -s .mvn/settings.xml -P release deploy --file pom.xml
