name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - shell: bash
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
        run: |
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes
      - name: Release with nexus-staging-maven-plugin
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          ossrh_login: ${{ secrets.ossrh_login }}
          ossrh_pass: ${{ secrets.ossrh_pass }}
        run: mvn -B -s .mvn/settings.xml -P release deploy --file pom.xml
