name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - shell: bash
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          gpg_private_key: ${{ secrets.gpg_private_key }}
          ossrh_login: ${{ secrets.ossrh_login }}
          ossrh_pass: ${{ secrets.ossrh_pass }}
        run: |
          echo "a: ${#gpg_private_key}"
          echo "b: ${#GPG_PASSPHRASE}"
          echo "c: ${#gpg_passphrase}"
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes
      - name: Release with nexus-staging-maven-plugin
        run: mvn -B -s .mvn/settings.xml -P release deploy -Dgpg_passphrase=$gpg_passphrase --file pom.xml
